@URL=http://localhost:8081

###
POST {{URL}}/users
Content-Type: application/json

{
    "username": "Chara",
    "email": "charadreemurr3571@gmail.com",
    "discord_username": "charadreemurr3571",
    "wallet_address": "8D1234567890",
    "github_username": "CharaDreemurr"
}
