version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_dashboard
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_dashboard_volume_data:/db

volumes:
  postgres_data:
  redis_data:
  redis_dashboard_volume_data:
