version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_dashboard
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_dashboard_volume_data:/db

volumes:
  mongodb_data:
  redis_data:
  redis_dashboard_volume_data:
